version: ‘3’
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi
      MYSQL_USER: user
      MYSQL_PASSWORD: demo
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql  # Persist MySQL data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 8082:80

  task-service:
    build: .
    container_name: task-service
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi
      MYSQL_USER: user
      MYSQL_PASSWORD: demo
      MYSQL_PORT: 3306
      AUTH0_AUDIENCE: task-service
      AUTH0_DOMAIN: https://dev-u34uch0wzt1tbai3.us.auth0.com/

    depends_on:
      - db